<?php

	use Illuminate\Database\Seeder;
	use Carbon\Carbon;

	class ActivityTableSeed extends Seeder
	{
		/**
		 * Run the database seeds.
		 *
		 * @return void
		 */
		public function run()
		{
			//
			$now = Carbon::now();
			$apply_end = $now->addDays(15);
			$start = $now->addDays(20);
			$end = $now->addDays(22);
			DB::table('activities')->insert([
				'user_id' => 1,
				'category_id' => 1,
				'achievement_id' => 1,
				'activity_video' => '["/video/snowboard.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Snowboard Challenge',
				'activity_url_name' => 'snowboard-challenge',
				'activity_description' => 'Snowboard Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 2,
				'category_id' => 3,
				'achievement_id' => 1,
				'activity_video' => '["/video/toy.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Toy maker Challenge',
				'activity_url_name' => 'toymaker-challenge',
				'activity_description' => 'Toy maker Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 3,
				'category_id' => 2,
				'achievement_id' => 1,
				'activity_video' => '["/video/chef.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Chef Challenge',
				'activity_url_name' => 'chef-challenge',
				'activity_description' => 'Chef Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 4,
				'category_id' => 1,
				'achievement_id' => 1,
				'activity_video' => '["/video/snowboard.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Snowboard Challenge',
				'activity_url_name' => 'snowboard-challenge2',
				'activity_description' => 'Snowboard Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 5,
				'category_id' => 1,
				'achievement_id' => 1,
				'activity_video' => '["/video/snowboard.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Snowboard Challenge',
				'activity_url_name' => 'snowboard-challenge3',
				'activity_description' => 'Snowboard Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 6,
				'category_id' => 2,
				'achievement_id' => 1,
				'activity_video' => '["/video/snowboard.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Snowboard Challenge',
				'activity_url_name' => 'snowboard-challenge4',
				'activity_description' => 'Snowboard Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 1,
				'category_id' => 2,
				'achievement_id' => 1,
				'activity_video' => '["/video/snowboard.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Snowboard Challenge',
				'activity_url_name' => 'snowboard-challenge5',
				'activity_description' => 'Snowboard Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
			DB::table('activities')->insert([
				'user_id' => 1,
				'category_id' => 2,
				'achievement_id' => 1,
				'activity_video' => '["/video/snowboard.mp4", "https://mdbootstrap.com/img/video/forest.mp4"]',
				'activity_name' => 'Snowboard Challenge',
				'activity_url_name' => 'snowboard-challenge6',
				'activity_description' => 'Snowboard Challenge',
				'activity_benefit' => '[{"pic":"/img/studio/abc.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description Benefit 1 descriptionBenefit 1 descriptionBenefit 1 descriptionBenefit 1 description"},{"pic":"/img/profile.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"},{"pic":"/img/studio/cooking.jpg","bg":"/img/Deepsea.jpeg","name":"Benefit 1","text":"Benefit 1 description"}]',
				'activity_prepare' => '<ul><li>eiei</li></ul>',
				'activity_difficult' => 'Basic',
				'activity_time_type' => 0,
				'activity_apply_start' => $now,
				'activity_apply_end' => $apply_end,
				'activity_start' => $start,
				'activity_end' => $end,
				'activity_routine_day' => '0',
				'activity_time_start' => '10:00',
				'activity_time_end' => '22:00',
				'activity_hour' => 16,
				'activity_price' => 3000,
				'activity_max' => 20,
				'activity_sponsors' => '[{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"},{"name":"spon","url":"/img/sponsor.png","link":"www.google.com"}]',
				'activity_location_name' => 'BMT',
				'activity_location' => 'https://www.google.com/maps/place/King+Mongkut%E2%80%99s+University+of+Technology+Thonburi/@13.65103,100.4931915,17z/data=!3m1!4b1!4m5!3m4!1s0x30e2a251bb6b0cf1:0xf656e94ff13324ad!8m2!3d13.6510248!4d100.4953802',
			]);
		}
	}
